=== IOoSKYLINEoOI/ITMO/ITMO.MarkupTechCourse2023/ITMO.MarkupTechCourse2023.XML/ITMO.MarkupTechCourse2023.XML.Lab2/lessons_DTD.dtd
<!ELEMENT TimeTable (Item+)>
<!ATTLIST Item id CDATA #REQUIRED>
<!ELEMENT Item (Teacher+, ClassTime, Begin, End)>
<!ELEMENT Teacher (FirstName, LastName)>
<!ELEMENT FirstName (#PCDATA)>
<!ELEMENT LastName (#PCDATA)>
<!ELEMENT ClassTime (#PCDATA)>
<!ELEMENT Begin (#PCDATA)>
<!ELEMENT End (#PCDATA)>

=== IOoSKYLINEoOI/ITMO/ITMO.MarkupTechCourse2023/ITMO.MarkupTechCourse2023.XML/ITMO.MarkupTechCourse2023.XML.Lab2/lesson.xml
<?xml version = "1.0" encoding ="utf-8"?>
<!DOCTYPE TimeTable SYSTEM "lessons_DTD.dtd">
<TimeTable>
    <Item id = "Курс №1">
        <Teacher>
            <FirstName>Имя преподавателя 1</FirstName>
            <LastName>Фамилия Преподавателя 1</LastName>
        </Teacher>
        <ClassTime>Время занятий</ClassTime>
        <Begin>Дата начала курса 1</Begin>
        <End>Дата окончания курса 1</End>
    </Item>
    <Item id = "Курс №2">
        <Teacher>
            <FirstName>Имя преподавателя 2</FirstName>
            <LastName>Фамилия Преподавателя 2</LastName>
        </Teacher>
        <ClassTime>Время занятий</ClassTime>
        <Begin>Дата начала курса 2</Begin>
        <End>Дата окончания курса 2</End>
    </Item>
    <Item id = "Курс №3">
        <Teacher>
            <FirstName>Имя преподавателя 3</FirstName>
            <LastName>Фамилия Преподавателя 3</LastName>
        </Teacher>
        <ClassTime>Время занятий</ClassTime>
        <Begin>Дата начала курса 3</Begin>
        <End>Дата окончания курса 3</End>
    </Item>
    <Item id = "Курс №4">
        <Teacher>
            <FirstName>Имя преподавателя 4</FirstName>
            <LastName>Фамилия Преподавателя 4</LastName>
        </Teacher>
        <ClassTime>Время занятий</ClassTime>
        <Begin>Дата начала курса 4</Begin>
        <End>Дата окончания курса 4</End>
    </Item>
</TimeTable>
